config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { registrations: 'registrations' , :omniauth_callbacks => "callbacks"}
	resources :worlds do
		resources :characters
	end
	resources :worlds do
		resources :sessions do
			resources :sessioncharacters
		end
	end
	resources :characters do
		resources :abilities
	end
	resources :characters do
		resources :items
	end

	get 'users/:id' => 'user#show'
	root "home#index"
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :archetype
  belongs_to :race
  belongs_to :world
  has_many :abilities, dependent: :destroy
  has_many :items, dependent: :destroy
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character = Character.find(params[:id])
    @abilities = Ability.where('character_id = ?',"#{@character.id}")
    @items = Item.where('character_id = ?',"#{@character.id}")
  end

  # GET /characters/new
  def new
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # POST /characters
  # POST /characters.json
  def create
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character = Character.new(character_params)
    if @character.exp>=0
      @character.level=1
    end
    if @character.exp>=300
      @character.level=2
    end
    if @character.exp>=500
      @character.level=3
    end
    if @character.exp>=1000
      @character.level=4
    end
    if @character.exp>=2000
      @character.level=5
    end
    if @character.exp>=5000
      @character.level=6
    end
    if @character.exp>=10000
      @character.level=7
    end
    if @character.exp>=20000
      @character.level=8
    end
    if @character.exp>=50000
      @character.level=9
    end
    if @character.exp>=100000
      @character.level=10
    end
    if (@character.strength + @character.vitality + @character.intelligence + @character.dexterity + @character.agility + @character.wisdom + @character.charisma) == @character.level
      respond_to do |format|
        if @character.save
          format.html { redirect_to @character, notice: 'Character was successfully created.' }
          format.json { render :show, status: :created, location: @character }
        else
          format.html { render :new }
          format.json { render json: @character.errors, status: :unprocessable_entity }
        end
      end
    else
      flash[:danger] = "Character stats must match level."
      render :new
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    if @character.exp>=0
      @character.level=1
    end
    if @character.exp>=300
      @character.level=2
    end
    if @character.exp>=500
      @character.level=3
    end
    if @character.exp>=1000
      @character.level=4
    end
    if @character.exp>=2000
      @character.level=5
    end
    if @character.exp>=5000
      @character.level=6
    end
    if @character.exp>=10000
      @character.level=7
    end
    if @character.exp>=20000
      @character.level=8
    end
    if @character.exp>=50000
      @character.level=9
    end
    if @character.exp>=100000
      @character.level=10
    end
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :world_id, :user_id, :level, :exp, :archetype_id, :race_id, :role, :strength, 
        :vitality, :intelligence, :dexterity, :agility, :wisdom, :charisma, :hp, :cp, :sp, :gp, :pp, :locX, :locY, :alive)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
      <%= form.label :world_id %><br/>
      <%= form.collection_select :world_id,  World.order('name ASC'), :id, :name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :exp %>
    <% if character.exp.nil? %>
      <%= form.number_field :exp, :value => 0 %>
    <% else %>
      <%= form.number_field :exp, :value => character.exp %>
    <% end %>
  </div>

  <div class="field">
      <%= form.label :archetype_id %><br/>
      <%= form.collection_select :archetype_id,  Archetype.order('name ASC'), :id, :name, include_blank: false %>
  </div>

  <div class="field">
      <%= form.label :race_id %><br/>
      <%= form.collection_select :race_id,  Race.order('name ASC'), :id, :name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :role, 'Class' %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :HP %>
    <% if character.hp.nil? %>
      <%= form.number_field :hp, :value => 0 %>
    <% else %>
      <%= form.number_field :hp, :value => character.hp %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <% if character.strength.nil? %>
      <%= form.number_field :strength, :value => 0 %>
    <% else %>
      <%= form.number_field :strength, :value => character.strength %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :vitality %>
    <% if character.vitality.nil? %>
      <%= form.number_field :vitality, :value => 0 %>
    <% else %>
      <%= form.number_field :vitality, :value => character.vitality  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :intelligence %>
    <% if character.intelligence.nil? %>
      <%= form.number_field :intelligence, :value => 0 %>
    <% else %>
      <%= form.number_field :intelligence, :value => character.intelligence  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :dexterity %>
    <% if character.dexterity.nil? %>
      <%= form.number_field :dexterity, :value => 0 %>
    <% else %>
      <%= form.number_field :dexterity, :value => character.dexterity  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :agility %>
    <% if character.agility.nil? %>
      <%= form.number_field :agility, :value => 0 %>
    <% else %>
      <%= form.number_field :agility, :value => character.agility  %>
    <% end %>

  </div>

  <div class="field">
    <%= form.label :wisdom %>
    <% if character.wisdom.nil? %>
      <%= form.number_field :wisdom, :value => 0 %>
    <% else %>
      <%= form.number_field :wisdom, :value => character.wisdom  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <% if character.charisma.nil? %>
      <%= form.number_field :charisma, :value => 0 %>
    <% else %>
      <%= form.number_field :charisma, :value => character.charisma  %>
    <% end %>
  </div>

  <%= form.hidden_field :gp, value: 5 %>

  <%= form.hidden_field :alive, value: true %>

  <%= form.hidden_field :played, value: 0 %>

  <div class="actions">
    <%= form.submit class:"btn btn-light" %>
  </div>

<% end %>

app/views/characters/_form2.html.erb
<%= form_with(model: character, local: true) do |form| %>
  <% if character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% character.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="field">
      <%= form.label :world_id %><br/>
      <%= form.collection_select :world_id,  World.order('name ASC'), :id, :name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :exp %>
    <% if character.exp.nil? %>
      <%= form.number_field :exp, :value => 0 %>
    <% else %>
      <%= form.number_field :exp, :value => character.exp %>
    <% end %>
  </div>

  <div class="field">
      <%= form.label :archetype_id %><br/>
      <%= form.collection_select :archetype_id,  Archetype.order('name ASC'), :id, :name, include_blank: false %>
  </div>

  <div class="field">
      <%= form.label :race_id %><br/>
      <%= form.collection_select :race_id,  Race.order('name ASC'), :id, :name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :role, 'Class' %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :HP %>
    <% if character.hp.nil? %>
      <%= form.number_field :hp, :value => 0 %>
    <% else %>
      <%= form.number_field :hp, :value => character.hp %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :strength %>
    <% if character.strength.nil? %>
      <%= form.number_field :strength, :value => 0 %>
    <% else %>
      <%= form.number_field :strength, :value => character.strength %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :vitality %>
    <% if character.vitality.nil? %>
      <%= form.number_field :vitality, :value => 0 %>
    <% else %>
      <%= form.number_field :vitality, :value => character.vitality  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :intelligence %>
    <% if character.intelligence.nil? %>
      <%= form.number_field :intelligence, :value => 0 %>
    <% else %>
      <%= form.number_field :intelligence, :value => character.intelligence  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :dexterity %>
    <% if character.dexterity.nil? %>
      <%= form.number_field :dexterity, :value => 0 %>
    <% else %>
      <%= form.number_field :dexterity, :value => character.dexterity  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :agility %>
    <% if character.agility.nil? %>
      <%= form.number_field :agility, :value => 0 %>
    <% else %>
      <%= form.number_field :agility, :value => character.agility  %>
    <% end %>

  </div>

  <div class="field">
    <%= form.label :wisdom %>
    <% if character.wisdom.nil? %>
      <%= form.number_field :wisdom, :value => 0 %>
    <% else %>
      <%= form.number_field :wisdom, :value => character.wisdom  %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :charisma %>
    <% if character.charisma.nil? %>
      <%= form.number_field :charisma, :value => 0 %>
    <% else %>
      <%= form.number_field :charisma, :value => character.charisma  %>
    <% end %>
  </div>

  <div class="field">
      <%= form.label :alive %>
      <%= form.check_box :alive %>
  </div>

  <%= form.hidden_field :gp, value: 5 %>

  <%= form.hidden_field :alive, value: true %>

  <%= form.hidden_field :played, value: 0 %>

  <div class="actions">
    <%= form.submit class:"btn btn-light" %>
  </div>

<% end %>

app/views/characters/edit.html.erb
<div class="container">

	<h1>Edit Character</h1>

	<%= render 'form2', character: @character %>

	<%= link_to 'Back', @character %> 

</div>

app/views/characters/index.html.erb
<div class="container">

  <h1>Characters</h1>

  <table class="table table-light shadow">
    <thead>
      <tr>
        <th>Name</th>
        <th>User</th>
        <th>Level</th>
        <th>Exp</th>
        <th>Arch</th>
        <th>Race</th>
        <th>Class</th>
        <th>Hp</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td><%= link_to character.name, character %></td>
          <td><%= character.user.name %></td>
          <td><%= character.level %></td>
          <td><%= character.exp %></td>
          <td><%= character.archetype.name %></td>
          <td><%= character.race.name %></td>
          <td><%= character.role %></td>
          <td><%= character.hp %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Character', new_character_path, class: "btn btn-light shadow" %>

</div>

app/views/characters/new.html.erb
<div class="container">

	<h1>New Character</h1>

	<%= render 'form', character: @character %>

	<%= link_to 'Back', characters_path, class:"btn btn-light" %>

</div>

app/views/characters/show.html.erb
<div class="container">

  <h1> <%= @character.name %> </h1>

  <div class="row">

    <div class="col-sm-6">

      <p><strong>User: </strong><%= @character.user.name %></p>

      <p><strong>World: </strong><%= @character.world.name %></p>

      <p><strong>Arch: </strong><%= @character.archetype.name %></p>

      <p><strong>Race: </strong><%= @character.race.name %></p>

      <p><strong>Class: </strong><%= @character.role %></p>

      <p><strong>Hp: </strong><%= @character.hp %></p>

      <% if @character.strength != 0 %>
        <p><strong>Str: </strong><%= @character.strength %></p>
      <% end %>

      <% if @character.vitality != 0 %>
        <p><strong>Vit: </strong><%= @character.vitality %></p>
      <% end %>

      <% if @character.intelligence != 0 %>
        <p><strong>Int: </strong><%= @character.intelligence %></p>
      <% end %>

      <% if @character.dexterity != 0 %>
        <p><strong>Dex: </strong><%= @character.dexterity %></p>
      <% end %>

      <% if @character.agility != 0 %>
        <p><strong>Agi: </strong><%= @character.agility %></p>
      <% end %>

      <% if @character.wisdom != 0 %>
        <p><strong>Wis: </strong><%= @character.wisdom %></p>
      <% end %>

      <% if @character.charisma != 0 %>
        <p><strong>Cha: </strong><%= @character.charisma %></p>
      <% end %>

    </div>

    <div class="col-sm-6">

      <p><strong>Level: </strong><%= @character.level %></p>

      <p><strong>Exp: </strong><%= @character.exp %></p>

      <p><strong>Cp: </strong><%= @character.cp %></p>

      <p><strong>Sp: </strong><%= @character.sp %></p>

      <p><strong>Gp: </strong><%= @character.gp %></p>

      <p><strong>Pp: </strong><%= @character.pp %></p>

      <p><strong>Alive: </strong><%= @character.alive %></p>
  
    </div>

  </div>

  <% if @character.user == current_user %>
    <%= link_to 'Edit', edit_character_path, class: "btn btn-light shadow" %>  
    <%= link_to 'Destroy', @character, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light shadow" %>
  <% end %>
  <br><br>

  <h2> Abilities </h2>

  <table class="table table-light shadow">
    <thead>
      <tr>
        <th>Phase</th>
        <th>Name</th>
        <th>Range</th>
        <th>Effect</th>
        <th>Flair</th>
        <th colspan="300"></th>
      </tr>
    </thead>
    <tbody>
      <% phase = ["Passive", "Active", "Free", "Reaction"] %>
      <% @abilities.each do |ab| %>
        <tr>
          <td><%= phase[ab.phase-1] %></td>
          <td><%= ab.name %></td>
          <td><%= ab.range %></td>
          <td><%= ab.effect %></td>
          <td><%= ab.flair %></td>
          <% if @character.user == current_user %>
            <td><%= link_to 'Edit', edit_character_ability_path(@character.id, ab.id) %> | <%= link_to 'Delete', character_ability_path(@character.id, ab.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @character.user == current_user %>
    <%= link_to 'Create an Ability', new_character_ability_path(@character.id), class: "btn btn-light shadow" %>
  <% end %>

  <br><br>
  <h2> Items </h2>
  <% @items.each do |item| %>
    <div class="card-columns">
      <div class="card shadow">
        <div class="card-body">
          <h4 class="card-title"><%= item.name %></h4>
          <p class="card-text"><%= item.description %></p>
          <p class="card-subtitle mb-2 text-muted">Durability: <%= item.uses %>/<%= item.durability %></p>
        </div>
      </div>
    </div>
  <% end %>
  <br>
</div>