config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { registrations: 'registrations' , :omniauth_callbacks => "callbacks"}
	resources :worlds do
		resources :characters
	end
	resources :worlds do
		resources :sessions do
			resources :sessioncharacters
		end
	end
	resources :characters do
		resources :abilities
	end
	resources :characters do
		resources :items
	end

	get 'users/:id' => 'user#show'
	root "home#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  belongs_to :character
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archetype.rb
class Archetype < ApplicationRecord
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :archetype
  belongs_to :race
  belongs_to :world
  has_many :abilities, dependent: :destroy
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :character
end

app/models/race.rb
class Race < ApplicationRecord
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :world
  has_many :sessioncharacters, dependent: :destroy
end

app/models/sessioncharacter.rb
class Sessioncharacter < ApplicationRecord
  belongs_to :character
  belongs_to :session
  validates :character_id, :presence => true, uniqueness: { scope: :session_id }
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  
	def self.from_omniauth(auth)
		where(provider:auth.provider,uid:auth.uid).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.email = auth.info.email
			user.name = auth.info.name
			user.password = Devise.friendly_token[0,20]
		end
	end
end

app/models/world.rb
class World < ApplicationRecord
  belongs_to :user
  has_many :sessions, dependent: :destroy
  has_many :worldcharacters, dependent: :destroy
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@characters = Character.order({ played: :asc })
  	@characters_deceased = Character.where('alive = ?',false)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # GET /items/new
  def new
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character = Character.find(params[:character_id])
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # POST /items
  # POST /items.json
  def create
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @item = Item.new(item_params)
    @character  = Character.find(params[:character_id])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @character, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character  = Character.find(params[:character_id])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @character, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @character  = Character.find(params[:character_id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @character, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :character_id, :description, :uses, :durability)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@characters = Character.where('user_id = ?',"#{@user.id}")
  	@worlds = World.where('user_id = ?',"#{@user.id}")
  	@sessions = Session.joins(charactersessions: :characters).where('user_id = ?',"#{@user.id}")
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  before_action :set_world, only: [:show, :edit, :update, :destroy]

  # GET /worlds
  # GET /worlds.json
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @worlds = World.all
  end

  # GET /worlds/1
  # GET /worlds/1.json
  def show
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @world = World.find(params[:id])
    @world_characters = Character.where('world_id = ?', params[:id])
    @world_sessions = Session.where('world_id = ?', params[:id])
  end

  # GET /worlds/new
  def new
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @world = World.new
  end

  # GET /worlds/1/edit
  def edit
    unless user_signed_in?
      redirect_to new_user_session_path
    end
  end

  # POST /worlds
  # POST /worlds.json
  def create
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @world = World.new(world_params)

    respond_to do |format|
      if @world.save
        format.html { redirect_to @world, notice: 'World was successfully created.' }
        format.json { render :show, status: :created, location: @world }
      else
        format.html { render :new }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worlds/1
  # PATCH/PUT /worlds/1.json
  def update
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    respond_to do |format|
      if @world.update(world_params)
        format.html { redirect_to @world, notice: 'World was successfully updated.' }
        format.json { render :show, status: :ok, location: @world }
      else
        format.html { render :edit }
        format.json { render json: @world.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worlds/1
  # DELETE /worlds/1.json
  def destroy
    unless user_signed_in?
      redirect_to new_user_session_path
    end
    @world.destroy
    respond_to do |format|
      format.html { redirect_to worlds_url, notice: 'World was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_world
      @world = World.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def world_params
      params.require(:world).permit(:name, :user_id, :description)
    end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/worlds_helper.rb
module WorldsHelper
end

app/views/items/_form.html.erb
<%= form_for([@character, @item]) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <%= form.hidden_field :character_id, value: @character.id %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :uses %>
    <%= form.number_field :uses %>
  </div>

  <div class="field">
    <%= form.label :durability %>
    <%= form.number_field :durability %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-light" %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="container">

	<h1>Editing Item</h1>

	<%= render 'form', item: @item %>
	
	<%= link_to 'Back', character_path(@character.id), class:"btn btn-light" %>

</div>

app/views/items/new.html.erb
<div class="container">

	<h1>New Item</h1>

	<%= render 'form', item: @item %>

	<%= link_to 'Back', character_path(@character.id), class:"btn btn-light" %>

</div>

app/views/user/show.html.erb
<div class="container">
	<h1><%= @user.name %></h1>

	<h2>Characters:</h2>

	<table class="table table-light shadow">
		<thead>
			<tr>
				<th>Name</th>
				<th>Level</th>
				<th>Race</th>
				<th>Archetype</th>
				<th>Class</th>
				<th colspan="300"></th>
			</tr>
		</thead>
		<tbody>
			<% @characters.each do |character| %>
				<tr>
					<td><%= link_to character.name, character %></td>
					<td><%= character.level %></td>
					<td><%= character.race.name %></td>
					<td><%= character.archetype.name %></td>
					<td><%= character.role %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<% if @user == current_user %>
		<td><%= link_to 'Create a Character', new_character_path(@user.id), class: "btn btn-light shadow" %></td>
	<% end %>

	<br><br>
	<h2>Worlds:</h2>

	<table class="table table-light shadow">
		<thead>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th colspan="300"></th>
			</tr>
		</thead>
		<tbody>
			<% @worlds.each do |world| %>
				<tr>
					<td><%= link_to world.name, world %></td>
					<td><%= world.description %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

</div>

app/views/worlds/_form.html.erb
<%= form_with(model: world, local: true) do |form| %>
  <% if world.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(world.errors.count, "error") %> prohibited this world from being saved:</h2>

      <ul>
      <% world.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form.label :name %>
  <div class="field">
    <%= form.text_field :name %>
  </div>

  <% if current_user.is_admin %>
    <div class="field">
      <%= form.label :user_id %>
        <%= form.collection_select :user_id,  User.order('name ASC'), :id, :name, include_blank: false %>
    </div>
    <% else %>
      <%= form.hidden_field :user_id, value: current_user.id %>
  <% end %>

  <%= form.label :description %>
  <div class="field">
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-light" %>
  </div>
<% end %>

app/views/worlds/edit.html.erb
<div class="container">

	<h1>Editing World</h1>

	<%= render 'form', world: @world %>

	<%= link_to 'Show', @world, class:"btn btn-light" %> 
	
	<%= link_to 'Back', worlds_path, class:"btn btn-light" %>

</div>

app/views/worlds/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <h1>Worlds</h1>

  <table class="table table-light shadow">
    <thead>
      <tr>
        <th>Name</th>
        <th>GM</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @worlds.each do |world| %>
        <tr>
          <td><%= link_to world.name, world %></td>
          <td><%= world.user.name %></td>
          <td><%= world.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New World', new_world_path , class: "btn btn-light shadow"%>

</div>

app/views/worlds/new.html.erb
<div class="container">

	<h1>New World</h1>

	<%= render 'form', world: @world %>

	<%= link_to 'Back', worlds_path, class:"btn btn-light" %>

</div>

app/views/worlds/show.html.erb
<div class="container">

	<h1><strong><%= @world.name %></strong></h1>

	<h4>DM: <%= @world.user.name %></h4>

	<p>
	  <%= @world.description %>
	</p>

	<h2>Characters</h2>
	<table class="table table-light shadow">
		<thead>
			<tr>
				<th>Name</th>
				<th>Level</th>
				<th>Race</th>
				<th>Archetype</th>
				<th>Class</th>
				<th>User</th>
				<th colspan="300"></th>
			</tr>
		</thead>
		<tbody>
			<% @world_characters.each do |character| %>
				<tr>
          			<td><%= link_to character.name, character %></td>
					<td><%= character.level %></td>
					<td><%= character.race.name %></td>
					<td><%= character.archetype.name %></td>
					<td><%= character.role %></td>
					<td><%= character.user.name %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= link_to "Add Character", new_character_path(@world.id), class: "btn btn-light shadow" %>	
	<br><br>

	<h2>Sessions</h2>
	<table class="table table-light shadow">
		<thead>
			<tr>
				<th>Name</th>
				<th>Started</th>
				<th>Ended</th>
				<th>Context</th>
				<th colspan="300"></th>
			</tr>
		</thead>
		<tbody>
			<% @world_sessions.each do |session| %>
				<tr>
          			<td><%= link_to session.name, session.world_id.to_s + '/sessions/' + session.id.to_s %></td>
					<td><%= session.ongoing %></td>
					<td><%= session.ended %></td>
					<td><%= session.context %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<%= link_to 'New Session', new_world_session_path(@world), class: "btn btn-light shadow" %> 
	<br><br>

	<% if @world.user == current_user %>
		<%= link_to 'Edit', edit_world_path(@world), class: "btn btn-light shadow" %> 
	<% end %>
	<%= link_to 'Back', worlds_path, class: "btn btn-light shadow" %>

</div>